<a href="https://colab.research.google.com/github/Resti000/learning_journal/blob/main/h8dsft_Linear_Algebra1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
a = [17,22,19]
vect_a = np.array(a)

In [4]:
vect_a

array([17, 22, 19])

In [5]:
b = [10,20,11]
c = [5,12,9]

vect_b = np.array(b)
vect_c = np.array(c)

In [6]:
vect_b

array([10, 20, 11])

In [7]:
vect_c

array([ 5, 12,  9])

In [8]:
vect_a + vect_b

array([27, 42, 30])

In [9]:
vect_b - vect_c

array([5, 8, 2])

In [10]:
vect_a.dot(vect_c)

520

In [11]:
vect_a * vect_b

array([170, 440, 209])

In [12]:
np.linalg.norm(vect_a)

33.67491648096547

In [13]:
result_dot_product = vect_a.dot(vect_b)
result_dot_product

819

In [14]:
cos_theta = result_dot_product / (np.linalg.norm(vect_a) * np.linalg.norm(vect_b))
cos_theta

0.9759590023331435

In [15]:
u = [2,5]
v = [3,1]

vect_uv = np.array([(u),(v)])

In [16]:
vect_uv

array([[2, 5],
       [3, 1]])