<a href="https://colab.research.google.com/github/Resti000/learning_journal/blob/main/h8dsft_Linear_Algebra3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import eig

A = np.array([[1,-1],[6,4]])
A

array([[ 1, -1],
       [ 6,  4]])

In [ ]:
eigval, eigvec = eig(A)

In [ ]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

In [ ]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])